### ISSUE TITLE
[Common] Clear the logs directory before running a TC

### ISSUE THREAD

**Issue by nik-redhat** [gluster/redant#980]
**Describe the bug**
The logs of any gluster operation are stored under `/var/log/glusterfs` directory, and currently, the logs are not cleared after the TC is finished running. This can cause some issues as listed below:
- With time, the directory size will become very big as the logs will increase by running TCs repetitively.
- Some, TCs grep the log file for validation, and if the logs are not cleared it may take up old data and return wrong results.

**Proposed Solution**
We can't clear the logs after the TC finishes because many times the user might want to check the logs and look for issues from them. Hence, it would be better to clear the logs directory at the beginning of the TC run, that is in the `Environment Setup` step itself. Both in the servers and clients.

**Comment by srijan-sivakumar** [comment]
We should make it configurable..so that based on user input ( maybe a cli arg or config input ), either the logs will be cleared or they'll be left as it is.
